server {
    listen       80;
    server_name  _;
    root   /usr/share/nginx/html;
    index  index.html;

    # SPA — تېپىلمىغان يول بولسا index.html غا قايتۇرۇش
    location / {
        try_files $uri $uri/ /index.html;
    }

    # static byloqlarni cache lash
    location ~* \.(?:js|css|woff2?|png|jpe?g|svg|ico)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
    }

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
}
